version: '3'
services:
  db:
    image: postgres:10.6
    # portsの指定、quoteなしだと、Unquoted port mapping not recommended と出る
    ports:
      - "19876:5432"
    environment:
      POSTGRES_USER: ringo
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ringo_tabetter_py
      # データベースファイルの置き場所をサブディレクトリにする
      PGDATA: /var/lib/postgresql/data/pgdata
    # データベースファイルの格納先を名前付きボリュームにする
    volumes:
      - ringo_data:/var/lib/postgresql/data

# 名前付きボリュームの設定
volumes:
  ringo_data: {}