# Generated by Django 4.1.1 on 2022-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweets_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastsearch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
